/**:
  ros__parameters:
    # Input topics handled/muxed.
    # For each topic:
    # - name    : name identifier to select the topic
    # - topic   : input topic of geometry_msgs::Twist type
    # - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
    # - priority: priority in the range [0, 255]; the higher the more priority over other topics
    topics:
      0:
        name    : navigation
        topic   : "/nav_vel"
        timeout : 1.0
        priority: 10
      1:
        name    : joystick
        topic   : "/joy_vel"
        timeout : 1.5
        priority: 100
      2:
        name    : keyboard
        topic   : "/key_vel"
        timeout : 1.5
        priority: 90
      3:
        name    : tablet
        topic   : "/tab_vel"
        timeout : 1.5
        priority: 100
    # Locks to stop the twist inputs.
    # For each lock:
    # - topic   : input topic that provides the lock; it must be of type std_msgs::Bool?!!!
    # - timeout : == 0.0 -> not used
    #              > 0.0 -> the lock is supposed to published at a certain frequency in order
    #                       to detect that the publisher is alive; the timeout in seconds allows
    #                       to detect that, and if the publisher dies we will enable the lock
    # - priority: priority in the range [0, 255], so all the topics with priority lower than it
    #             will be stopped/disabled
    locks:
      0:
        name    : pause
        topic   : pause_navigation
        timeout : 0.0
        # Same priority as joystick control, so it'll not block it.
        priority: 100
      1:
        name    : loop_closure
        topic   : stop_closing_loop
        timeout : 0.0
        priority: 200
      2:
        name    : joystick
        topic   : joy_priority
        timeout : 0.0
        priority: 100
    joystick:
      priority: True
      turbo:
        linear_forward_min  : 0.5
        linear_forward_max  : 1.0
        linear_backward_min : 0.25
        linear_backward_max : 0.5
        angular_min : 0.7
        angular_max : 1.2
        steps       : 4
